version: '3.5'

services:
  wireguardwgui:
    build: .
    container_name: wireguardwgui
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=odmin
      - WGUI_PASSWORD=OpasswordO
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      - PUID=1000
      - PGID=1000
      - WGUI_PERSISTENT_KEEPALIVE=25
      - WGUI_CONFIG_FILE_PATH=/config/wg0.conf
    ports:
#      - 51820:51820/udp
      - 5000:5000
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./db:/app/db
      - ./config:/config
