version: '3.5'

services:
  wireguard:
    build: .
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=odmin
      - WGUI_PASSWORD=OpasswordO
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      - WGUI_PERSISTENT_KEEPALIVE=25
      - WGUI_CONFIG_FILE_PATH=/config/wg0.conf
    ports:
      - 51820:51820/udp
      - 5000:5000
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./db:/app/db
      - ./config:/config
#      - /lib/modules:/lib/modules
      - ./etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - wireguard_default
      - zabbix_server
#        ipv4_address: 172.20.0.5
    restart: unless-stopped

networks:
  wireguard_default:
    name: wireguard_default
    driver: bridge
  zabbix_server:
    name: zabbix_server
    driver: bridge
